In [3]:
#import data
import pandas as pd
df = pd.read_csv('Sleep_Analysis')
df.head()

,Age,Gender,meals/day,physical illness,screen time,bluelight filter,sleep direction,exercise,smoke/drink,beverage,sleep time
0,22,Male,two,no,2hrs,yes,west,sometimes,no,Tea,6.7575
1,22,Female,three,no,3-4 hrs,no,south,no,no,Coffee,8.0000
2,23,Male,three,no,3-4 hrs,no,south,no,no,Tea,8.0000
3,23,Female,two,no,1-2 hrs,no,east,sometimes,no,Coffee,6.5000
4,22,Male,three,no,more than 5,yes,east,sometimes,yes,Tea and Coffee both,6.0000

In [18]:
#get number of rows
num_rows = len(df)

In [19]:
#calculate average sleep time
sleep_time_average = df['sleep time'].mean()

In [20]:
#calculate percent using bluelight filter
bluelight_filter_percentage = len(df[df['bluelight filter'] == 'yes'])/num_rows

In [2]:
#seperate data for only men
male_df = df[df['Gender'] == 'Male']
male_df.head()

,Age,Gender,meals/day,physical illness,screen time,bluelight filter,sleep direction,exercise,smoke/drink,beverage,sleep time
0,22,Male,two,no,2hrs,yes,west,sometimes,no,Tea,6.7575
2,23,Male,three,no,3-4 hrs,no,south,no,no,Tea,8.0000
4,22,Male,three,no,more than 5,yes,east,sometimes,yes,Tea and Coffee both,6.0000
5,22,Male,two,no,2-3 hrs,yes,west,sometimes,no,Tea,6.7575
6,22,Male,four,no,1-2 hrs,yes,south,yes,no,none of the above,7.0000

In [15]:
#get number of men rows
num_mrows = len(male_df)

In [16]:
#calculate average male sleep time
male_sleep_time_average = male_df['sleep time'].mean()

In [17]:
#calculate male percent using bluelight
male_bluelight_filter_percentage = len(male_df[male_df['bluelight filter'] == 'yes'])/num_mrows

In [21]:
#seperate data for women only
female_df = df[df['Gender'] == 'Female']
female_df.head()

,Age,Gender,meals/day,physical illness,screen time,bluelight filter,sleep direction,exercise,smoke/drink,beverage,sleep time
1,22,Female,three,no,3-4 hrs,no,south,no,no,Coffee,8.0
3,23,Female,two,no,1-2 hrs,no,east,sometimes,no,Coffee,6.5
7,24,Female,three,yes,4-5 hrs,no,east,sometimes,no,Tea,6.5
9,23,Female,three,no,more than 5,yes,north,yes,yes,Tea and Coffee both,7.0
10,28,Female,three,no,0-1 hrs,yes,north,yes,no,Tea,6.5

In [22]:
#get number of female rows
num_frows = len(female_df)

In [23]:
#calculate female average sleep time
female_sleep_time_average = female_df['sleep time'].mean()

In [24]:
#get percent of females using bluelight filter
female_bluelight_filter_percentage = len(female_df[female_df['bluelight filter'] == 'yes'])/num_frows

In [26]:
#put all data collected into a dataframe
gender_summary = pd.DataFrame({'Average Sleep Time': [sleep_time_average], 
                                 '% Using Bluelight': [bluelight_filter_percentage],
                                 'Male Average Sleep Time': [male_sleep_time_average],
                                 'Male % Using Bluelight': [male_bluelight_filter_percentage],
                                 'Female Average Sleep Time': [female_sleep_time_average],
                                 'Female % Using Bluelight': [female_bluelight_filter_percentage]
                                })
gender_summary

,Average Sleep Time,% Using Bluelight,Male Average Sleep Time,Male % Using Bluelight,Female Average Sleep Time,Female % Using Bluelight
0,6.7575,0.543478,6.801731,0.576923,6.916667,0.444444

In [27]:
#get dataframe of those using bluelight
using_bluelight_df = df[df['bluelight filter'] == 'yes']

In [28]:
#get dataframe of those not using bluelight
not_using_bluelight_df = df[df['bluelight filter'] == 'no']

In [30]:
#calcutate average sleep time of those using the bluelight filter
average_sleep_time_using_blue = using_bluelight_df['sleep time'].mean()
print("The average sleep time for those using bluelight filters is " + str(average_sleep_time_using_blue))

The average sleep time for those using bluelight filters is 6.6606

In [32]:
#calcutate average sleep time of those not using the bluelight filter
average_sleep_time_not_using_blue = not_using_bluelight_df['sleep time'].mean()
print("The average sleep time for those not using bluelight filters is " + str(average_sleep_time_not_using_blue))

The average sleep time for those not using bluelight filters is 6.872857142857142